### ISSUE TITLE
Transforming response data before firing the success action

### ISSUE THREAD

**Issue by lraivio** [agraboso/redux-api-middleware#10]
Would it be possible to add a way to transform the response data before passing it to the success action?
The use case I have in mind would be to camelize all the data keys before the data reaches reducers.
Like in https://github.com/rackt/redux/blob/master/examples/real-world/middleware/api.js#L35.

If `[CALL_API]` had a `transform` property (function to transform the response data) or something similar it would work on other use cases as well.

**Comment by agraboso** [comment]
This `transform` function you propose is something I already had in mind.

As of now, `redux-api-middleware` uses `normalizr` to process the json response of the server because that's what the original real-world example code did. Then @bs1180 made a PR &mdash; which I merged &mdash; to allow using `arrayOf` of `normalizr` schemas. Now you are asking for yet another way of post-processing the response.

The change to `transform`s should be pretty trivial, and would help decouple the API call from the processing of the response. From the point of view of the consumer of this module, it would only require changing occurrences of `schema: aSchema` inside `[CALL_API]` to something like `transform: (json) => normalize(json, aSchema)`.

**Comment by lraivio** [comment]
Cool if you already had that in mind.
The solution you propose sounds good.

**Comment by agraboso** [comment]
@lraivio: see v0.6.0.

**Comment by lraivio** [comment]
Awesome!
Thank you very much @agraboso for the quick work on this!
And also for the whole project in general.
