### ISSUE TITLE
Option timeout does not work

### ISSUE THREAD

**Issue by nclong87** [agraboso/redux-api-middleware#211]
Hi guys, I tried to add timeout into options field like that:
```
[RSAA]: {
      endpoint: endpoints.getLearningWords(),
      method: 'GET',
      options: { timeout: 3 },
      headers: { 'Content-Type': 'application/json' },
```
but it didn't affect at all, do I need to configure at another place?
Thanks

**Comment by darthrellimnad** [comment]
`timeout` is not actually part of the standard `fetch` API (https://github.github.io/fetch/).  `node-fetch` however, does implement a timeout option I think, which is what the RSAA docs are referring to I believe (agree that section of docs is a bit confusing though!)

If you need a client-side fetch timeout option for browsers, you'll need to find or write a fetch polyfill that implements your desired "timeout" behavior... but I would recommend handling timeouts on the server primarily, and allow the browser's default timeout to kick in if things start to hang.  Arbitrarily "canceling" a fetch request may also involve using AbortController to actually close the open connection, and probably easier to handle that in a seperate middleware extension at that point, since this is not a concern of the fetch API, and would need refs to both the fetch Promise, and the assigned AbortController, which may mix with app or buisness specific logic.

- https://github.com/whatwg/fetch/issues/20
- https://davidwalsh.name/fetch-timeout

**Comment by nclong87** [comment]
Thanks for your very clear answer
