### ISSUE TITLE
ReferenceError: fetch is not defined after upgrading

### ISSUE THREAD

**Issue by josemigallas** [agraboso/redux-api-middleware#219]
> I asked this already at [Stackoverflow](https://stackoverflow.com/questions/54008747/redux-api-middleware-throws-fetch-is-not-defined) but will do it here again for the sake of visibility.

I recently upgraded `redux-api-middleware` from 2.3.0 to 3.0.1 When running my tests with `jest@22.2.1` I get this `ReferenceError`:

```
    ReferenceError: fetch is not defined
    
      19 | export function sortPolicyChain (payload: Array<ChainPolicy>): SortPolicyChainAction {
      20 |   return { type: 'SORT_POLICY_CHAIN', payload }
    > 21 | }
      22 |
      23 | export type UpdatePolicyInChainAction = { type: 'UPDATE_POLICY_IN_CHAIN', policyConfig: ChainPolicy }
      24 | export function updatePolicyInChain (policyConfig: ChainPolicy): UpdatePolicyInChainAction {
    
      at Object.<anonymous> (node_modules/redux-api-middleware/lib/index.cjs.js:404:3)
      at Object.<anonymous> (app/javascript/src/Policies/actions/PolicyChain.jsx:21:27)
      at Object.<anonymous> (spec/javascripts/Policies/actions/PolicyChain.spec.jsx:3:20)
```

The stacktrace points to this line in **PolicyChain.jsx**:
```javascript
    export function fetchChain (serviceId: string): RSSAAction {
      return {
        [RSAA]: {
          endpoint: `/admin/api/services/${serviceId}/proxy/policies.json`,
          method: 'GET',
          credentials: 'same-origin',
          types: [REQUEST, SUCCESS, FAILURE]
        }
      }
    }
```
According to the [documentation here][1]:

> If provided, the fetch option must be a function that conforms to the
> Fetch API. **Otherwise, the global fetch will be used.**

But it looks like the global fetch can't be found. Any ideas?

Relevant code at https://github.com/3scale/porta/pull/463.

  [1]: https://www.npmjs.com/package/redux-api-middleware#rsaafetch
  [2]: https://github.com/3scale/porta/pull/463/files

**Comment by darthrellimnad** [comment]
I don't believe node implements a global fetch method like browsers do, so you may need to add a standards compliant version to jest's runtime environment to match behavior.

Not totally sure why an upgrade to v3 would cause this though, since the internal isomorphic-fetch dependency was removed in v2 I believe. Usually, this can be handled with a [setupScripts.js](https://facebook.github.io/create-react-app/docs/running-tests#initializing-test-environment) file (when using `react-scripts`), or a [setupFiles](https://jestjs.io/docs/en/configuration.html#setupfiles-array) config when using Jest directly.

Here, you can create `global.fetch` and `window.fetch` value for unit and/or  integration tests using something like [`isomorphic-fetch`], or a mock implementation like [`jest-fetch-mock`](https://www.npmjs.com/package/jest-fetch-mock).

Additionally, with `redux-api-middleware`, you can often simply stub the `dispatch` method of the store used by a unit test, since these tests mainly need to verify that dispatched RSAAs are well formed and match an expected RSAA object.

More info on setting up Jest with a fetch implementation can be found in the following issue:
https://github.com/facebook/create-react-app/issues/967

Hope this helps :)

**Comment by montanajob** [comment]
This is also a problem for isomorphic apps. What makes it especially problematic is that the code where the global fetch is assumed happens in the global scope of middleware.js, so an error is thrown as soon redux-api-middleware is included (ie, on startup). So we don't even get a chance to pass in fetch from `node-fetch` or the like, as we were in 2.3.0, and our app fails out of the gate. 

I propose waiting until within `createMiddleware()` to set the default value of `fetch`, assuming it wasn't passed in through `options`.

**Comment by Jedidiah** [comment]
Hitting this same problem trying to use this in a Gatsby app. The build fails as fetch is undefined.

**Comment by Jedidiah** [comment]
For anyone else wanting to get this working with Gatsby, I got rid of the error by adding isomorphic-fetch as a webpack plugin in `gatsby-node.js`.

```
exports.onCreateWebpackConfig = ({ actions }) => {
  actions.setWebpackConfig({
    plugins: [
      new webpack.ProvidePlugin({
        fetch: path.resolve(path.join(__dirname, "node_modules/isomorphic-fetch/fetch-npm-node"))
      })
    ]
  });
};
```

**Comment by nason** [comment]
@darthrellimnad is right about `fetch`

Any suggestions as to how this could be handled better?

**Comment by essensx** [comment]
I have the same issue with nextjs, as node does not have `fetch`. Because of `defaults` trying to access `fetch`, you can't set your own fetch implementation, which renders the functionality unusable in node env. I think the easier solution would be to just check if `fetch` is defined, before trying to set it into the object.

**Comment by iamandrewluca** [comment]
Use `createMiddleware` with your own fetch compilant function
https://github.com/agraboso/redux-api-middleware#createmiddlewareoptions

**Comment by essensx** [comment]
It will not work, as the build fails due to undefined `fetch`.

https://i.imgur.com/iIq2XeI.png

**Comment by iamandrewluca** [comment]
@nason I would suggest to make a breaking change and remove `apiMiddleware` and let users replace it with
```js
const apiMiddleware = createMiddleware({ fetch: /* any fetch compilat library */ })
```
This way we get rid of any global instances.

**Comment by essensx** [comment]
Hmm, in my opinion this seems a bit harsh, considering that most of the consumers of the library probably use polyfills to resolve such issues.

If implementing `globalThis` proposal is a bit of a hassle, I think we could actually implement a simpler - to evaluate user-defined fetch implementation first (if set), then try to use global `fetch` 🤔 In this case, the library should be usable in all use cases.

Any thoughts?

**Comment by iamandrewluca** [comment]
Long story short. I have a fix. But I don't know how exactly it will behave.
The difference between v2 and v3 that throws error I think it has something to do with `'use strict';` mode.
And I'm still for that to deprecate `apiMiddleware` in favor of `createMiddleware`.

https://github.com/agraboso/redux-api-middleware/pull/251

**Comment by iamandrewluca** [comment]
Released in https://github.com/agraboso/redux-api-middleware/releases/tag/v3.2.1

**Comment by essensx** [comment]
Awesome! Though i suggest investing in proper solution, as we will still need to update the babel preset eventually.. Sorry for not contributing, did not have the time

**Comment by iamandrewluca** [comment]
> i suggest investing in proper solution

Proper sollution I think is to drop apiMiddleware in favor of createMiddleware.
And get rid of all global dependencies.

> we will still need to update the babel preset eventually

I'll take a look again when will have some time.
