### ISSUE TITLE
Final release 1.0.x

### ISSUE THREAD

**Issue by barrystaes** [agraboso/redux-api-middleware#45]
Before we can make breaking changes, or add features, we should issue a proper final 1.0 release. 

Issues to address;

 - [x] #19 The release of 1.0.0-beta3 may not be built correctly
 - [x] ~~#35 'Unhandled promise rejection' on Firefox~~

Did i miss anything?

/cc @agraboso @riophae @ericmash @JoelOtter @smazurov @sgoll

**Comment by JoelOtter** [comment]
So I'm unable to reproduce #35 now as I'm doing my AJAX 'manually' (Thunk and Axios). I wasn't doing anything particularly strange with the library, though, and it was happening in multiple versions of FF, so hopefully someone can reproduce it.

**Comment by barrystaes** [comment]
Ok so #28 is fixed and we cant reproduce #35.

:cake:  
This concludes 1.0.0-beta3 and the next release is 1.0.0 following the semver notation.
Congratulations @agraboso and thanks for your efforts!

**Comment by barrystaes** [comment]
In anticipation of the release, a quick note on upgrading: in `package.json` change the line
````
redux-api-middleware: '1.0.0-beta3',
```
to read
```
redux-api-middleware: '^1.0.0',
```
and you'll automatically have the latest compatible version after running `npm install`.

**Comment by sylvainlap** [comment]
I read in the issue that it could be have problems between this middleware and thunk. Is it still the case with v1 ? Is there a specific order to load the middlewares (thunk before api-middleware) ?

Thanks

**Comment by barrystaes** [comment]
@sylvainlap Questions are best answered, and asked, in the relevant issue.

@agraboso Lets release v1.0.0 on [npm](https://www.npmjs.com/package/redux-api-middleware)?

**Comment by sylvainlap** [comment]
@barrystaes this issue is about v1, I though it was relevant.

**Comment by agraboso** [comment]
v1.0.0 is now published on `npm`.

@barrystaes: there was a test that failed in my machine because I had Apache running and the test isn't mocking the appropriate endpoint &mdash; it succeeded once I turned Apache off. It is the test entitled `apiMiddleware must dispatch an error request FSA on a request error` starting in line 1092 of `text/index.js`. The weird thing is that I tried adding
```js
  const api = nock('http://127.0.0.1')
                .get('/api/users/1')
                .reply(404);
```
at the beginning of the test and it kept failing, but succeeded if I switched `404` for `301`. Something to have a look at for the future.
