### ISSUE TITLE
Add redux-optimist

### ISSUE THREAD

**Issue by fresk-nc** [agraboso/redux-api-middleware#55]
Do you want to add support "optimistically apply actions" with module [redux-optimist](https://github.com/ForbesLindesay/redux-optimist)?

**Comment by barrystaes** [comment]
Is this not already supported?
From the docs it appears a root optimist reducer (wrapping other reducers) and adding the optimist key in each FSA that your RSAA makes would work.. would it not?

Have not (yet) used it myself though.

**Comment by fresk-nc** [comment]
How can I add `optimist: {type: COMMIT, id: transactionID}` for success action?

**Comment by barrystaes** [comment]
A quick search tells me t[hat since 0.2.1 you can put `optimist` in `meta`](https://github.com/mathieudutour/redux-optimist-promise/issues/2#issuecomment-172329828) so its a FSA compliant.

So i guess something like..
```
{
  [CALL_API]: {
    endpoint: 'http://www.example.com/api/users',
    method: 'GET',
    types: [
      'REQUEST',
      {
        type: 'SUCCESS',
        payload: (action, state, res) => {
          // whatever
        },
        meta: (action, state, res) => {
          optimist: {type: COMMIT, id: res.transactionID}          //    <---
        }
      },
      'FAILURE'
    ]
  }
}
```
But ofcourse for REQUEST and FAILURE you would have to also use optimist keys, and instead of getting the transaction id returned in a response you may want to use action or state to get it.

**Comment by mmiszy** [comment]
@barrystaes did you ever manage to implement this?

**Comment by barrystaes** [comment]
@mmiszy Not this specific example. And I never put redux-api-middleware in actual production use so my experience using it is/was very limited. Having todays experience i'd probably just use a ES6 promise in the called action to achieve this.
