### ISSUE TITLE
Fetch cannot be mocked

### ISSUE THREAD

**Issue by cevou** [agraboso/redux-api-middleware#75]
Hi,

at the moment requests send through this middleware cannot be mocked (through fetch-mock). This is due to the fact, that fetch is imported from isomorphic-fetch rather then using the global fetch function.
The standard defined the fetch function as global. isomorphic-fetch registers it as a global function in nodejs and in the browser.
It would be great if you could just load the module but not import the fetch function. I could also provide a PR for that.

Best,
Christoph

**Comment by migueloller** [comment]
Not only can `fetch` not be mocked but this is also causing errors for React Native bundles due to [#125](https://github.com/github/fetch/issues/125#issuecomment-169118755) and [5667](https://github.com/facebook/react-native/issues/5667). It would be best to leave it up to the developer to provide a fetch polyfill. That way, if they have an environment that already implements fetch, this error won't happen.

This is doesn't only happen in React Native. It will happen on any environment that already has fetch and requires a package, like `redux-api-middleware` that also polyfills fetch.

**Comment by agraboso** [comment]
The `next` branch (which will lead to version 2) removes `isomorphic-fetch` in favor of the global `fetch`.
